APP_CATEGORIES = {"LIFESTYLE": ["Com.sktelecom.minit", "Kal.FlightInfo", "app.hybirds.skypeople", "cc.pacer.androidapp",
                                "cheehoon.ha.particulateforecaster", "coinone.co.kr.official", "com.CouponChart",
                                "com.F1.ShinSG", "com.TouchEn.mVaccine.webs", "com.aboutjsp.thedaybefore",
                                "com.agoda.mobile.consumer", "com.aia.vitality.kr", "com.airbnb.android",
                                "com.airvisual", "com.ak.android.akmall", "com.alibaba.aliexpresshd",
                                "com.amanefactory.totsukitoka", "com.aminlogic.NavigationCompass", "com.app.shd.pstock",
                                "com.application_4u.qrcode.barcode", "com.bcf.coinstep", "com.bientus.cirque.android",
                                "com.blockfolio.blockfolio", "com.btckorea.bithumb",
                                "com.buzzni.android.subapp.shoppingmoa", "com.cafe24.ec.plusandar01",
                                "com.caloriecoin.wallet", "com.cashwalk.cashwalk", "com.chanel.weather.forecast.accu",
                                "com.chbreeze.jikbang4a", "com.cj.twosome", "com.cjkoreaexpress", "com.cjoshppingphone",
                                "com.coffeebeankorea.android", "com.coupang.mobile", "com.croquis.zigzag",
                                "com.cultsotry.yanolja.nativeapp", "com.delta.mobile.android", "com.dencreak.spbook",
                                "com.diningcode", "com.dnt7.threeW", "com.dominicosoft.coinmaster",
                                "com.dunamu.exchange", "com.dunamu.stockplus", "com.dunamu.trading",
                                "com.easy.currency.extra.androary", "com.ebay.kr.auction", "com.ebay.kr.g9",
                                "com.ebay.kr.gmarket", "com.ediya.coupon", "com.elevenst", "com.elevenst.deals",
                                "com.espn.score_center", "com.fitstar.pt", "com.fridaynoons.playwings",
                                "com.global.tarotmaster", "com.google.android.apps.maps", "com.gsr.gs25",
                                "com.habb.thankq", "com.hanabank.ebk.channel.android.hananbank",
                                "com.hanaskcard.paycla", "com.hanaskcard.rocomo.potal", "com.hanbit.fitday",
                                "com.hanbit.rundayfree", "com.hanwhalife.mobilecenter", "com.happy.mobilepop",
                                "com.hcom.android", "com.himart.main", "com.hmallapp", "com.hnsmall",
                                "com.hogangnono.hogangnono", "com.homeplus.myhomeplus", "com.hotelscombined.mobile",
                                "com.hpapp", "com.hyundaicard.appcard", "com.hyundaioilbank.android",
                                "com.ibillstudio.thedaycouple", "com.ibk.onebankA", "com.idincu.ovey.android",
                                "com.inbody2014.inbody", "com.interpark.shop", "com.interpark.tour.mobile.main",
                                "com.jasonmg.market09", "com.kakao.i.connect", "com.kakaobank.channel",
                                "com.kayak.android", "com.kbankwith.smartbank", "com.kbcard.cxh.appcard",
                                "com.kbcard.kat.liivmate", "com.kbcard.kbkookmincard", "com.kbstar.kbbank",
                                "com.kbstar.minibank", "com.kbstar.smartotp", "com.kbstar.starpush",
                                "com.kebhana.hanapush", "com.korail.talk", "com.kr.hollyscoffee",
                                "com.kt.android.showtouch", "com.kt.gigagenie.mobile", "com.kt.ktauth",
                                "com.ktcs.whowho", "com.ktshow.cs", "com.lcacApp", "com.lge.lifetracker",
                                "com.lguplus.mobile.cs", "com.linkzen.app", "com.looket.soim",
                                "com.lotte.lottedutyfree", "com.lotte.lpay", "com.lottemart.lmscp",
                                "com.lottemembers.android", "com.lpoint.moalock", "com.lunatouch.eyefilter.pro",
                                "com.makeshop.powerapp.jinsence81", "com.makeshop.powerapp.xexymix",
                                "com.mapmyrun.android2", "com.mo2o.alsa", "com.moms.momsdiary", "com.mozzet.lookpin",
                                "com.mrpizza.android", "com.mrt.ducati", "com.mysmilepay.app",
                                "com.nate.android.portalmini", "com.nhn.android.moneybook", "com.nhn.android.nmap",
                                "com.nhn.land.android", "com.nhnent.payapp", "com.nike.plusgps",
                                "com.northcube.sleepcycle", "com.nsmobilehub", "com.olleh.android.oc2",
                                "com.omnitel.android.lottewebview", "com.org.yakult", "com.pione.questiondiary",
                                "com.popularapp.periodcalendar", "com.pub.fm", "com.rainist.banksalad2",
                                "com.realbyteapps.moneymanagerfree", "com.sampleapp", "com.samsung.android.oneconnect",
                                "com.samsung.android.spay", "com.samsung.ssmobile", "com.samsungfire.insurance",
                                "com.samsungpop.android.mpop", "com.sec.android.app.shealth", "com.shcard.smartpay",
                                "com.shilladutyfree", "com.shinhan.sbanking", "com.shinhancard.smartshinhan",
                                "com.skmc.okcashbag.home_google", "com.skplanet.weatherpong.mobile", "com.skt.aladdin",
                                "com.skt.logii.widget", "com.skt.skaf.OA00026910", "com.skt.smartbill",
                                "com.sktelecom.tauth", "com.sktelecom.tsmartpay", "com.smartro.gongcha", "com.smg.spbs",
                                "com.socialapps.homeplus", "com.soilbonus.goodoilfamily", "com.sportractive",
                                "com.ssg.serviceapp.android.egiftcertificate", "com.starbucks.co", "com.strava",
                                "com.tenfingers.seouldatepop", "com.tinder", "com.tmon", "com.tms", "com.ton.tarotofoz",
                                "com.tourbaksaapp.app", "com.tourlive", "com.towneers.www", "com.uniqlo.kr.catalogue",
                                "com.unsin", "com.uplus.baseballhdtv", "com.weeds.tillionpanel.full", "com.wemakeprice",
                                "com.whox2.lguplus", "com.wooribank.pib.smart", "com.wooribank.pot.smart",
                                "com.wooribank.smart.mwib", "com.wooribank.smart.wwms", "com.wooricard.smartapp",
                                "com.wooriwm.mugsmart", "com.wooriwm.txsmart", "com.wr.alrim", "com.xiaomi.hm.health",
                                "com.xiaomi.smarthome", "com.yuanta.helloyuanta", "com.yuanta.tradarm",
                                "de.flixbus.app", "handasoft.mobile.divination", "hyundai.hi.smart.android.activity",
                                "kr.ac.kaist.bab", "kr.backpackr.me.idus", "kr.co.bitsonic", "kr.co.burgerkinghybrid",
                                "kr.co.cjone.app.lockscreen", "kr.co.company.hwahae", "kr.co.emart.emartmall",
                                "kr.co.gscaltex.gsnpoint", "kr.co.hanamembers.hmscustomer",
                                "kr.co.ivlog.mobile.app.cjonecard", "kr.co.keypair.keywalletTouch",
                                "kr.co.kiwiplus.kiwi.kiwimom", "kr.co.lgfashion.lgfashionshop.v28",
                                "kr.co.mercurykorea", "kr.co.openit.openrider", "kr.co.psynet",
                                "kr.co.samsungcard.mpocket", "kr.co.srail.app", "kr.co.ssg", "kr.or.kftc.mobileapt2you",
                                "kt.co.ktmmobile", "kvp.jjy.MispAndroid320",
                                "losebellyfat.flatstomach.absworkout.fatburning",
                                "lt.spectrofinance.spectrocoin.android.wallet", "net.daum.android.map",
                                "net.giosis.shopping.sg", "net.ib.android.smcard", "net.skyscanner.android.main",
                                "nh.smart.signone", "sam.myanycar.samsungFire", "sixpack.sixpackabs.absworkout",
                                "sk.com.shopping", "stonykids.baedaltong.season2", "uplus.membership",
                                "viva.republica.toss", "com.SunHan", "com.WeTogether", "com.android.calendar",
                                "com.android.hotwordenrollment.okgoogle", "com.gdragon.pod.leeson", "com.kakao.home",
                                "com.kt.olleh.storefront", "com.lge.sizechangable.weather", "com.luga",
                                "com.samsung.android.calendar", "com.samsung.android.samsungpay.gear",
                                "com.samsung.android.weather", "com.sec.android.app.billing",
                                "com.sec.android.app.clockpackage", "com.sec.android.app.samsungapps",
                                "com.shinhan.global.vn.sclub", "com.show.greenbill", "com.skt.skaf.A000Z00040",
                                "com.skt.skaf.OA00018282", "com.skt.skaf.OA00199800", "com.smhk.boomerang",
                                "kr.ac.kaist.kyotong", "kr.co.kbo.redss.app", "kr.pe.javarss.barcodewallet2",
                                "net.daum.android.solcalendar", "net.giosis.shopping.hub", "nh.smart"],
                  "AUTO_AND_VEHICLES": ["ch.sbb.mobile.android.b2c", "com.astroframe.seoulbus", "com.djbus",
                                        "com.dwlife.drinkingcolor", "com.ebcard.bustago", "com.encar.encarMobileApp",
                                        "com.encardirect.app", "com.google.android.projection.gearhead", "com.greencar",
                                        "com.kakao.cp.driver", "com.kakao.taxi", "com.kakao.wheel.driver",
                                        "com.kscc.scxb.mbl", "com.kscc.xzz.mbl", "com.kt.mtmoney",
                                        "com.locnall.KimGiSa", "com.nbdproject.macarong", "com.skn.zamong2",
                                        "com.skt.tmap.ku", "com.ubercab", "de.hafas.android.db", "kr.co.cardoc",
                                        "kr.co.kbc.cha.android", "kr.co.vcnc.tada", "kt.navi", "net.orizinal.subway",
                                        "socar.Socar", "teamDoppelGanger.SmarterSubway",
                                        "com.httpdongbu_directcar.dbdirect", "com.skt.skaf.l001mtm091"],
                  "EDUCATION": ["com.Classting", "com.belugaedu.amgigorae", "com.brainbow.peak.app",
                                "com.carrotenglish.rptest", "com.hellotalk", "com.imcompany.school2",
                                "com.kcic.oneminjapanese", "com.mathpresso.qandateacher", "com.moiseum.dailyart2",
                                "com.naver.naveraudio", "com.nhn.android.naverdic", "com.qualson.realclass",
                                "com.stn.mobile_player", "kr.ac.kaist.coursemos.android", "kr.co.sigongedu.memo",
                                "kr.co.yanadoo.mobile", "net.carrotenglish.ctm", "com.diotek.sec.lookup.dictionary",
                                "com.omega.dic.es", "com.sec.android.app.dictionary"],
                  "GAME": ["com.Monthly23.SwipeBrickBreaker", "com.bandainamcoent.onepiecetresurecruisekr",
                           "com.kakaogames.friendsKing", "com.kakaogames.friendsTower", "com.kakaogames.gnss",
                           "com.nexon.da3", "com.nexon.nsc.maplem", "com.outfit7.mytalkingtomfree",
                           "com.pearlabyss.blackdesertm", "com.playrix.gardenscapes", "com.pubg.krmobile",
                           "com.puzzlegames.collection.puzzle", "com.sundaytoz.kakao.anipang3.service",
                           "com.sundaytoz.kakao.wbb", "com.supercell.clashroyale", "com.tinyco.potter",
                           "com.wellgames.ss", "kr.aos.com.aprogen.hng.fortressm", "com.samsung.android.game.gamehome",
                           "com.samsung.android.game.gametools"],
                  "PRODUCTIVITY_AND_BUSINESS": ["com.Slack", "com.adobe.reader", "com.albamon.app",
                                                "com.alphainventor.filemanager", "com.androidrocker.callblocker",
                                                "com.credu.ml", "com.dropbox.android",
                                                "com.estmob.android.sendanywhere", "com.evernote",
                                                "com.google.android.apps.ads.publisher", "com.google.android.apps.docs",
                                                "com.google.android.apps.docs.editors.docs",
                                                "com.google.android.apps.docs.editors.sheets",
                                                "com.google.android.apps.docs.editors.slides",
                                                "com.google.android.apps.m4b", "com.google.android.calendar",
                                                "com.google.android.keep", "com.infraware.office.link",
                                                "com.intsig.camscanner", "com.jobkorea.app", "com.jobplanet.kr.android",
                                                "com.jushine.cstandard", "com.microsoft.office.excel",
                                                "com.microsoft.office.onenote", "com.microsoft.office.powerpoint",
                                                "com.microsoft.office.word", "com.microsoft.rdc.android",
                                                "com.microsoft.skydrive", "com.naver.nozzle",
                                                "com.nhn.android.navermemo", "com.nhn.android.ndrive",
                                                "com.samsung.android.app.notes", "com.samsung.android.email.provider",
                                                "com.samsung.android.galaxycontinuity", "com.samsung.knox.securefolder",
                                                "com.sec.android.inputmethod", "com.skt.prod.cloud",
                                                "com.sktelecom.tguard", "com.socialnmobile.dictapps.notepad.color.note",
                                                "com.surpax.ledflashlight.panel", "com.sweettracker.smartparcel",
                                                "com.teamup.teamup", "com.teamviewer.teamviewer.market.mobile",
                                                "com.tf.thinkdroid.viewer", "com.truemobile.ipdisk",
                                                "kr.co.alba.webappalba.m", "kr.co.hiworks.messenger",
                                                "kr.co.hiworks.mobile", "kr.co.rememberapp", "kr.co.rinasoft.howuse",
                                                "kr.co.saramin.SalaryCalc", "lg.uplusbox", "net.slideshare.mobile",
                                                "org.isoron.uhabits", "com.hancom.office.editor.sec",
                                                "com.imoxion.sensmobile", "com.linkedin.android.jobs.jobseeker",
                                                "com.noknok.android.mfac.service", "com.nsds.myphoneandme"],
                  "TOOLS": ["com.ahnlab.v3mobileplus", "com.ahnlab.v3mobilesecurity.soda", "com.asus.remotelink.full",
                            "com.atsolution.android.uotp2", "com.cleanmaster.mguard", "com.digibites.accubattery",
                            "com.estsoft.alyac", "com.fiberthemax.OpQ2keyboard", "com.finedigital.finewifiremocon",
                            "com.google.android.apps.authenticator2", "com.google.android.apps.translate",
                            "com.google.android.calculator", "com.google.android.gms",
                            "com.google.android.googlequicksearchbox", "com.lge.lgpay", "com.lonelycatgames.Xplore",
                            "com.meonria.scientificcalc", "com.mi.android.globalFileexplorer", "com.miui.calculator",
                            "com.mobidia.android.mdm", "com.naver.labs.translator", "com.necta.wifimousefree",
                            "com.samsung.android.app.watchmanager", "com.samsung.android.geargplugin",
                            "com.samsung.android.gearoplugin", "com.samsung.android.lool",
                            "com.samsung.android.mobileservice", "com.samsung.android.sidegesturepad",
                            "com.samsung.android.voc", "com.sec.android.app.myfiles",
                            "com.sec.android.app.popupcalculator", "com.sec.android.app.voicenote",
                            "com.sec.android.easyMover", "com.skt.prod.phonebook", "org.cohortor.gstrings",
                            "org.swadhin.app", "android.example.com.tflitecamerademo",
                            "catchpower.gogo.blackholeaddons", "com.android.apps.tag", "com.android.bluetooth",
                            "com.android.calculator2", "com.android.captiveportallogin",
                            "com.android.companiondevicemanager", "com.android.contacts", "com.android.documentsui",
                            "com.android.htmlviewer", "com.android.nfc", "com.android.phone",
                            "com.android.providers.downloads", "com.android.providers.media",
                            "com.android.server.telecom", "com.android.settings", "com.android.soundrecorder",
                            "com.android.updater", "com.android.vending", "com.clip.getapp", "com.edgeblock.edgeblock",
                            "com.facebook.appmanager", "com.fingerprints.fido.asm",
                            "com.google.android.packageinstaller", "com.google.android.setupwizard", "com.lge.clock",
                            "com.lge.phonemanagement", "com.lge.qhelp", "com.lge.qmemoplus", "com.lge.qremote",
                            "com.lge.shutdownmonitor", "com.lge.smartcover", "com.lge.smartsharepush",
                            "com.lge.updatecenter", "com.lge.voicerecorder", "com.lge.wifisettings", "com.samsung.SMT",
                            "com.samsung.android.MtpApplication", "com.samsung.android.app.advsounddetector",
                            "com.samsung.android.app.galaxyfinder", "com.samsung.android.app.memo",
                            "com.samsung.android.app.reminder", "com.samsung.android.app.scrollcapture",
                            "com.samsung.android.app.smartcapture", "com.samsung.android.app.soundpicker",
                            "com.samsung.android.app.taskedge", "com.samsung.android.authfw",
                            "com.samsung.android.bixby.agent", "com.samsung.android.bixby.wakeup",
                            "com.samsung.android.contacts", "com.samsung.android.da.daagent",
                            "com.samsung.android.edgelightingeffectunit", "com.samsung.android.goodlock",
                            "com.samsung.android.mateagent", "com.samsung.android.pluginrecents",
                            "com.samsung.android.samsungpass", "com.samsung.android.samsungpassautofill",
                            "com.samsung.android.scloud", "com.samsung.android.sconnect",
                            "com.samsung.android.themestore", "com.samsung.app.highlightplayer",
                            "com.sec.android.app.taskmanager", "com.sec.android.app.vepreload",
                            "com.sec.android.daemonapp", "com.sec.android.easyMover.Agent",
                            "com.sec.android.mimage.photoretouching", "com.sec.android.wallpapercropper2",
                            "com.skp.clink.invoke", "com.skt.prod.phone", "com.skt.prod.tphonelite",
                            "com.skt.t_smart_charge", "com.sonyericsson.pws", "com.sonyericsson.soundenhancement",
                            "com.sonymobile.android.contacts", "com.tarkarn.denialcall", "com.tv.remote.controletv.tv",
                            "com.vlingo.midas", "com.wssyncmldm", "devian.tubemate.v3", "org.tensorflow.demo"],
                  "PHOTOGRAPHY": ["com.alensw.PicFolder", "com.artifyapp.timestamp", "com.campmobile.snow",
                                  "com.commsource.beautyplus", "com.cyworld.camera", "com.fotoable.enstyle",
                                  "com.google.android.apps.photos", "com.kakao.cheez", "com.linecorp.b612.android",
                                  "com.linecorp.foodcam.android", "com.lyrebirdstudio.collage", "com.oss.mcam",
                                  "com.photofunia.android", "com.sec.android.gallery3d", "com.sonyericsson.album",
                                  "com.sonymobile.moviecreator.rmm", "com.ster.photo.surgery", "ph.app.instasave",
                                  "photoeditor.layout.collagemaker", "com.android.camera", "com.android.gallery3d",
                                  "com.aviary.android.feather", "com.lge.camera", "com.miui.gallery",
                                  "com.samsung.android.visionintelligence", "com.sec.android.app.camera",
                                  "com.sec.android.app.camera.avatarauth", "com.sonyericsson.android.camera"],
                  "SOCIAL_AND_COMMUNICATION": ["com.andr.evine.who", "com.android.chrome",
                                               "com.briniclemobile.wibeetalk", "com.btb.minihompy",
                                               "com.buzzvil.adhours", "com.cashslide", "com.dcinside.app",
                                               "com.discord", "com.enabledaonsoft.thecamp", "com.facebook.katana",
                                               "com.facebook.orca", "com.google.android.apps.messaging",
                                               "com.google.android.gm", "com.google.android.talk",
                                               "com.instagram.android", "com.kakao.story", "com.kakao.talk",
                                               "com.kickstarter.kickstarter", "com.linkedin.android",
                                               "com.nexon.nxplay", "com.nhn.android.band", "com.nhn.android.blog",
                                               "com.nhn.android.mail", "com.nhn.android.navercafe", "com.opera.browser",
                                               "com.ppomppu.android", "com.samsung.accessory",
                                               "com.sec.android.app.sbrowser", "com.sec.spp.push",
                                               "com.skt.prod.dialer", "com.skt.tdatacoupon", "com.skype.raider",
                                               "com.snapchat.android", "com.sonelli.juicessh", "com.teamblind.blind",
                                               "com.tencent.mm", "com.tumblr", "com.vaultmicro.kidsnote",
                                               "com.vidyo.VidyoClient", "com.whatsapp", "gogolook.callgogolook2",
                                               "jp.naver.line.android", "kr.ac.kaist.portal",
                                               "kr.co.vcnc.android.couple", "kreditdata.kreditjob",
                                               "net.daum.android.cafe", "net.daum.android.daum",
                                               "net.daum.android.tistoryapp", "org.telegram.messenger",
                                               "com.android.browser", "com.android.incallui", "com.android.mms",
                                               "com.samsung.android.incallui", "com.samsung.android.messaging",
                                               "com.samsung.android.service.livedrawing",
                                               "com.sonymobile.android.dialer", "kr.co.vcnc.betweendate.date",
                                               "net.hibrain.apps.android.hibrainnet"],
                  "ENTERTAINMENT": ["com.appgate.gorealra", "com.camobile.akb48mail", "com.cgv.android.movieapp",
                                    "com.delphicoder.flud", "com.frograms.watcha",
                                    "com.google.android.apps.youtube.kids", "com.google.android.play.games",
                                    "com.google.android.videos", "com.google.android.youtube", "com.imbc.mini",
                                    "com.interpark.app.ticket", "com.kt.otv", "com.megabox.mop", "com.morp.arirangVV",
                                    "com.mxtech.videoplayer.ad", "com.mxtech.videoplayer.pro", "com.naver.vapp",
                                    "com.netflix.mediaclient", "com.nexon.handsplus", "com.nhn.android.naverplayer",
                                    "com.qiyi.video.pad", "com.quvideo.xiaoying",
                                    "com.samsung.everland.android.mobileApp", "com.scatterlab.sol", "com.skb.btvmobile",
                                    "com.skb.smartrc", "com.skmnc.gifticon", "com.sonyericsson.xhs",
                                    "gg.op.lol.android", "kr.co.captv.pooqV2", "kr.co.kbs.kong",
                                    "kr.co.lottecinema.lcm", "kr.co.ticketlink.cne",
                                    "org.leetzone.android.yatsewidgetfree", "tv.jamlive", "tv.twitch.android.app",
                                    "video.player.videoplayer", "zettamedia.bflix", "com.samsung.android.video",
                                    "com.sec.android.app.dmb", "com.sec.android.app.videoplayer", "sixclk.newpiki"],
                  "MUSIC_AND_AUDIO": ["com.appmind.radios.jp", "com.behringer.android.control.app.m32q",
                                      "com.cocoradio.country.jp", "com.fundevs.app.mediaconverter",
                                      "com.gomtv.gomaudio", "com.google.android.apps.youtube.music",
                                      "com.google.android.music", "com.iloen.melon", "com.jaybirdsport.audio",
                                      "com.kakao.music", "com.mnet.app", "com.naver.vibe", "com.nhn.android.music",
                                      "com.sec.android.app.music", "com.shazam.android", "com.soribada.android",
                                      "com.soundbrenner.pulse", "fm.qingting.qtradio", "kr.ebs.bandi",
                                      "radiotime.player", "skplanet.musicmate", "tunein.player", "com.lge.music",
                                      "com.samsung.radio", "com.samsung.voiceserviceplatform",
                                      "com.sec.android.app.soundalive"],
                  "BOOKS_AND_REFERENCE": ["com.bambuna.podcastaddict", "com.clem.nhkradio",
                                          "com.cnn.mobile.android.phone", "com.godpeople.GPBIBLE",
                                          "com.initialcoms.ridi", "com.kakao.page", "com.kyobo.ebook.samsung",
                                          "com.medium.reader", "com.nhn.android.nbooks", "com.nhn.android.search",
                                          "com.nhn.android.webtoon", "com.ptculi.tekview", "com.skt.skaf.OA00050017",
                                          "com.sony.nfx.app.sfrc", "com.twitter.android", "flipboard.boxer.app",
                                          "fm.castbox.audiobook.radio.podcast", "kr.ac.libit.kaist",
                                          "kr.co.aladin.ebook", "kr.co.ypbooks.app", "mok.android",
                                          "net.daum.android.webtoon", "org.wikipedia", "com.sktechx.xviewer"]}
APPS_LAUNCHER = [
    'com.sec.android.app.launcher', 'com.lge.launcher3', 'com.google.android.apps.nexuslauncher', 'com.android.systemui'
]
